### ISSUE TITLE
example cannot load

### ISSUE THREAD

**Issue by mxgbs** [niessner/Opt#108]
Hi,

I build opt on windows 10, 64bits, VS2015, Have set OPT_DIR=%~dp0
"%OPT_DIR%\common\optMake.bat" "%OPT_DIR%\..\..\terra" "%OPT_DIR%\." "true" and run that .bat file. After builing, opt.dll shows in \Optlang\Opt\API\release\bin. I guess that means the building is successful. However, when I tried to open the example via VS2015, following error occurs. 

Documents\Optlang\Opt\examples\arap_mesh_deformation\arap_mesh_deformation.vcxproj : error  : Unable to read the project file "arap_mesh_deformation.vcxproj".
\Documents\Optlang\Opt\examples\arap_mesh_deformation\arap_mesh_deformation.vcxproj(34,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 7.5.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I don't have CUDA 7.5 installed, what I have is CUDA 9.0. Do you know what change should I make to let it import the right CUDA? Thanks.

**Comment by Mx7f** [comment]
Install CUDA 7.5, as it is a dependency for Opt. 

Alternatively, try to get it to work with 9.0 by changing things that depend on 7.5 to things that depend on 9.0. You have the line numbers in the error message, or you can search the project files.

**Comment by mxgbs** [comment]
Thank you. I didn't notice there is another line in vcxproj which I didn't
change. Now it's loaded. However, multiple errors come when trying to
compile. I tried to include the directory of Opt.h but it didn't work. Also
have no idea how to fix that C2440 error.
Remaking Opt.dll
1>  <buffer>:1:10: fatal error: '..\..\API\release\include\Opt.h' file not
found
1>  #include "..\..\API\release\include\Opt.h"
1>           ^
1>  compilation of included c code failed
1>
1>  stack traceback:
1>  [C]: in function 'registercfile'
1>  C:\Users\zdevito\terra\src\terralib.lua:3357: in function 'includec'
1>  ..\..\API\src\createWrapper.t:69: in main chunk
1>          1 file(s) moved.
1>  The system cannot find the file specified.
1>          1 file(s) moved.
1>  ..\..\API\release\bin\Opt.dll
1>  1 File(s) copied
1>  ..\..\API\release\lib\Opt.lib
1>  1 File(s) copied
1>  0 File(s) copied
1>  main.cpp
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(86):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'bool (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(86):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(86):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'size_t (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(86):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(87):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'bool (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(87):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(87):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'size_t (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(87):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(88):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'bool (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(88):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(88):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'size_t (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(88):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(89):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'bool (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(89):
note: None of the functions with this name in scope match the target type
1>c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(89):
error C2440: 'specialization': cannot convert from 'overloaded-function' to
'size_t (__cdecl OpenMesh::ArrayKernel::* )(void) const'
1>
c:\users\dengya\documents\optlang\opt\examples\external\openmesh\include\openmesh\core\mesh\polyconnectivity.hh(89):
note: None of the functions with this name in scope match the target type

**Comment by Mx7f** [comment]
Most of those errors are with OpenMesh. The version we distributed was compiled with VS2013, it is possible you will need to compile it yourself if you wish to use it with (like in #105).

Have you tried any of the non-mesh examples to see if OpenMesh is the only issue?
